@baseUrl = http://localhost:3002
@token = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InBlcGVvYjEyQGdtYWlsLmNvbSIsInN1YiI6MjMsImlhdCI6MTc1MDIxNDA5OSwiZXhwIjoxNzUwMjE3Njk5fQ.i8IneqONnyxiHn_tEK7bbvp7AL-95fApVjCBdT_-Wbw'
GET {{baseUrl}}/users/

###

GET {{baseUrl}}/users/2

###
POST {{baseUrl}}/users/create
Content-Type: application/json

{
  "name": "alo",
  "email": "pedro@gmail.com",
  "password": "123456"
  }

###

PATCH  {{baseUrl}}/users/2
Content-Type: application/json
 
{
  "name": "alo updated",
  "email": "pedro@update.com"
}

###

GET {{baseUrl}}/user-permissions/get-permission
Authorization: Bearer {{token}}
