version: '3.8'

services:
  api:
    build: .
    ports:
      - '3002:3002'
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5433
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=nest
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nest
    ports:
      - '5433:5433'
