version: '3.8'

services:
  api:
    build: .
    ports:
      - '3002:3002'
    environment:
      - PORT=3002
      - DATABASE_HOST=db
      - DATABASE_PORT=5433
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=123456
      - DATABASE_NAME=postgres
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: postgres
    ports:
      - '5433:5432'
 